---

apiVersion: v1
kind: Service
metadata:
  name: hello-http-world
spec:
  selector:
    app: hello-http-world
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-http-world
spec:
  selector:
    matchLabels:
      app: hello-http-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-http-world
    spec:
      containers:
      - name: hello-http-world
        image: nginx:latest
        ports:
        - containerPort: 80
